### ISSUE TITLE
Pixel 3 console TX not worked

### ISSUE THREAD

**Issue by pingwuu** [Peter-Easton/android-debug-cable-howto#7]
Hi,
I build my adapter for pixel 3, now minicom console can output phone's kernel log, but I can not input anything。
Anything I missed? thanks.

My adapter connection as below, and my USB2TTL signal is 1.8V:
USB2TTL GND  <---> TypeC Adapter's A1.
USB2TTL RXD  <---> TypeC Adapter's A8
USB2TTL TXD  <---> TypeC Adapter's B8

**Comment by pingwuu** [comment]
For uart tx worked, Need change any kernel configure or bootcmd parameter?
Thanks.

**Comment by samueldr** [comment]
Hi,

> my USB2TTL signal is 1.8V

Good thing you gave this information. While the TTL logic level is not specified in the main text, it [links to a 3.3V TTL Serial Cable](https://www.sparkfun.com/products/12977).

This makes me believe that you're able to get TX because 3.3V, while overwhelming the 1.8V adapter, is fine. Though RX might not work because while it's trying real hard, there is not 1.8V is not enough.

In my instance, my serial adapter is using a 3.3V TTL adapter too. I would hazard a guess the same for others who followed the guide.

With that said. There is a lot of advice online stating 1.8V should be used with phones. That they will be damaged otherwise. It is unclear to me, at this point, whether this holds true for the Pixel type-c serial cable or not.

**Comment by pingwuu** [comment]
Hi @samueldr ,

Thanks for your reply. I changed TTL logic level to 3.3v, it seems Phone's RX is not worked. Maybe I need change another type-c adapter and try again.

**Comment by pingwuu** [comment]
Using build kernel, both TX and RX worked. Maybe factory has some security option for console RX enable.
